---
output: github_document
bibliography: "references.bib"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tsExtremes package tutorial

<!-- badges: start -->

<!-- badges: end -->

The package tsExtremes includes functions for studying extreme features of heavy-tailed time series.
It can be used to compute estimates of the tail index, the extremal index or cluster lengths of the series. These are statistics of the series summarizing the magnitude of extreme records, and the number of concomitant records.

## Installation

<!-- You can install the released version of tsExtremes from [CRAN](https://CRAN.R-project.org) with: -->

To get started, install the package from Github using the command:

``` r
devtools::install_github('GBuritica/tsExtremes')
```

## R Package tutorial

This package tutorial includes two main windows on:

1.  Tail index inference
    -   In this vignette you will learn how to compute estimates of the tail index $\alpha$ of the series. The implementation is based on the Hill-type estimators in [@dehaan:mercadier:zhou:2016].

2.  Cluster inference
    -   In this vignette you will learn how to implement block estimates of cluster statistics; see [@buritica:mikosch:wintenberger:2021]. We consider the example of the extremal index based on the estimator proposed in [@buritica:meyer:mikosch:wintenberger:2021], and also an example of cluster lengths [@buritica:wintenberger:2024].

## References
